### ISSUE TITLE
Why can't I start on my PC?

### ISSUE THREAD

**Issue by Aleks-Ale** [chall3ng3r/Squix-Display-FontConverterV3#1]
![2020-12-10_14-21-02](https://user-images.githubusercontent.com/69778440/101766299-a5ea6d00-3af3-11eb-89f9-50bdbc4dfea0.png)

**Comment by chall3ng3r** [comment]
Hi,
I checked, try the following command line which also mentions the Class Path parameter to current folder,
`java -cp ./ FontConverterV3 "Tahoma" 14 r > font-tahoma.h`

Hope this will work for you and do share the result.

**Comment by Aleks-Ale** [comment]
Thank you for your attention!
Unfortunately, changing the command didn't change anything.
> java -cp ./ FontConverterV3 "Tahoma" 14 r > font-tahoma.h

![2020-12-11_21-10-07 (2)](https://user-images.githubusercontent.com/69778440/101940329-62792700-3bf7-11eb-885d-bc1ef8440566.png)
When I use full path fot FontConverterV3.java 
E:\squixfont>java -cp E:\squixfont\FontConverterV3.java "Tahoma" 14 r > font-tahoma.h
Error: Could not find or load main class Tahoma

At this time, I can rename the file FontConverterV3.java to _FonTTTTtConverterV3.java_" , but the answer is the same.
E:\squixfont>java -cp E:\squixfont\FontConverterV3.java "Tahoma" 14 r > font-tahoma.h
Error: Could not find or load main class Tahoma

As I can see, java -h - 
-cp <class search path of directories and zip/jar files>
ZIP or JAR, not .java?
Any ideas?

**Comment by chall3ng3r** [comment]
The Java runtime searches for compiled binary containing the class. If you explore the code, you can see that main class is not inside any namespace, so it should work as posted in example or the command line I provided.

Maybe move the folder to c: or another path, to see if it fixes the problem.

I have tried different combos, and even unpacked the same binary from release section to mg desktop, ran it by copy pasting the command, it worked.

**Comment by Aleks-Ale** [comment]
could you please check your java version?
I tested versions 7 and 8 32 bit and 64. 
Command line and .cmd file.
I changed the location of the FontConverterV3.java LetterData.java files directory.
java -cp ./FontConverterV3 "Tahoma" 14 r > font-tahoma.h
Code execution has the same answer.
C:\squixfont>C:\progra~2\Java\jre7\bin\java.exe -cp ./FontConverterV3 "Tahoma" 14 r  1>font-tahoma.h
Error: Could not find or load main class Tahoma
Мaybe I need additional software besides the installed Java for Windows version 8 Update 271 from java.com?

**Comment by Aleks-Ale** [comment]
jdk-15.0.1 installed now
L:\squixfont>javac -version
javac 15.0.1

L:\squixfont>java -version
java version "15.0.1" 2020-10-20
Java(TM) SE Runtime Environment (build 15.0.1+9-18)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.1+9-18, mixed mode, sharing)

L:\squixfont>java.exe -cp ./ FontConverterV3 "Tahoma" 14 r > font-tahoma.h
Error: Could not find or load main class FontConverterV3
Caused by: java.lang.ClassNotFoundException: FontConverterV3

I removed the space character in the file path:

L:\squixfont>java.exe -cp ./FontConverterV3 "Tahoma" 14 r > font-tahoma.h
Error: Could not find or load main class Tahoma
Caused by: java.lang.ClassNotFoundException: Tahoma

**Comment by chall3ng3r** [comment]
I have following Java version:
```
PS C:\Temp> java -version
openjdk version "1.8.0_242-release"
OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
OpenJDK 64-Bit Server VM (build 25.242-b01, mixed mode)
```
Try with the following command, 

`java -jar FontConverterV3.jar`

Lastly, compiling the code again on your PC.

**Comment by Aleks-Ale** [comment]
where to find FontConverterV3.jar?
FontConverterV3.java exist only 

L:\squixfont>java -jar FontConverterV3.jar
Error: Unable to access jarfile FontConverterV3.jar

**Comment by chall3ng3r** [comment]
Yes, sorry about that, that file doesn't exist. I searched and suggested what was written there.

Can you try with OpenJDK?
