### ISSUE TITLE
Converted Google Font Not Working

### ISSUE THREAD

**Issue by tmargot** [chall3ng3r/Squix-Display-FontConverterV3#2]
Hi,

I am having an issue getting my converted font to work with the esp8266-oled-ssd1306 library (https://github.com/ThingPulse/esp8266-oled-ssd1306).  I tried your online Squix Display Tool Font Converter and the downloaded file works fine, but when I tried to I convert a Google font (Teko-bold.ttf) the output doesn't seem to work.

Noting that that the site has a library version selection option and the FontConverterV3 readme does not mention one, could this be the issue? 

Command line used: java FontConverterV3 c:\font\Teko-Bold.ttf 24 r > c:\font\Font_Google_Teko_Bold-28.h

I have attached a zip containing the files. 

- Calligraffitti_Regular_28.h is the working download from your site
- Teko-Bold.ttf is the original Google font file
- Font_Google_Teko_Bold-28.h is the output of FontConverterV3.

[files.zip](https://github.com/chall3ng3r/Squix-Display-FontConverterV3/files/14823789/files.zip)

Any help would be much appreciated! And thank you for this tool.

**Comment by tmargot** [comment]
I have since opened the file generated "Font_Google_Teko_Bold-28.h" and it appears that it has output just Arial?

**Comment by chall3ng3r** [comment]
Hi,

Let me analyze the files you've shared.

**Comment by chall3ng3r** [comment]
Hello, I checked and it seems you're supplying the parameters incorrectly.

You need to install the font first, and then use it's name which is registered in system's font registry, you can't use the font file directly. 

For your case, the font you shared is named "Teko" in Windows (you can see font name in window when you open the font file). Then use the command as follows:

`java FontConverterV3 "Teko" 24 b > c:\font\Font_Google_Teko_Bold-28.h`

**Comment by tmargot** [comment]
Thank you for the reply. I see, did not get that from the instructions, but also wondered why there was no font file extensions. Thanks again, much appreciated.

**Comment by chall3ng3r** [comment]
You're welcome. I've updated the readme for the same.

**Comment by tmargot** [comment]
Thanks again, and for the update.
